services:
  proyecto-ia2:
    build: .
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: proyecto-ia2
    ports:
      - "8004:8002"
      - "2224:22"
      - "11435:11435"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    networks:
      - red_ia

  postgres:
    image: pgvector/pgvector:pg15
    container_name: ia_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ia_support
    ports:
      - "5432:5432"
    networks:
      - red_ia

networks:
  red_ia:
    external: true